---
title: "test tableR code"
author: "R.G. Thomas"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 11pt
geometry: "left=3cm,right=5cm,top=1cm,bottom=2cm"
output:
  pdf_document:
    number_sections: true
    highlight: tango
    keep_tex: true
    includes:
      in_header: "~/shr/preamble.tex"
---
```{r include=F, echo=F}
# clear env: objects and packages
rm(list = ls())
options(
  knitr.kable.NA = "", dplyr.summarise.inform = FALSE,
  dplyr.print_max = 1e9, knitr.table.format = "latex"
)
library(pacman)
p_load(janitor, kableExtra, tidyverse, knitr, lubridate, readxl)

opts_chunk$set(
  warning = FALSE, message = FALSE, echo = FALSE, fig.width = 3.2,
  fig.height = 3, results = "asis", dev = "pdf",
  opts_chunk$set(cache.path = "cache/")
)
source("~/shr/zz.tools.R")
options(scipen = 1, digits = 2)
```

\input{/Users/zenn/shr/zz.tools.tex}

```{r echo=F}
source("t2.R")
```
```{r }

p1 <- sample_n(penguins, 100) |>
  dplyr::select(
    species, flipper_length_mm, sex,
    body_mass_g, bill_length_mm, island
  ) |>
  dplyr::mutate(flp = flipper_length_mm > 197)
p1[100, "island"] <- NA

theme_npg <- list(
  foreground = c("black", "black", "black", "black"),
  background = c(
    "#f0efd4",
    "#e8e6bc",
    "#f0efd4",
    "#f0efd4"
  )
)
theme_nejm <- list(
  foreground = c("black", "black", "black", "black"),
  background = c("#fff7e9", "white", "#fff7e9", "white")
)

theme_green <- list(
  foreground = c("black", "black", "black", "black"),
  background = c("#99cfa8", "#d4f0dc", "#94ebad", "yellow")
)
theme_simple <- list(
  foreground = c("black", "black", "black", "black"),
  background = c("cyan", "blue", "green", "yellow")
)
theme_bw <- list(
  foreground = c("black", "black", "black", "black"),
  background = c("white", "white", "white", "white")
)
```
```{r }
tab0 <- table1(sex ~ island,
  data = p1,
  theme = theme_green, layout = "console", fname = "ptab0", digits = 3,
  pvalue = FALSE
)
tab0 <- table1(sex ~ island,
  data = p1,
  theme = theme_green, layout = "console", fname = "ptab0", digits = 3,
  pvalue = FALSE
)

tab1 <- table1(sex ~ island + flp + body_mass_g + bill_length_mm, data = p1)  |>
latex(theme = theme_nejm, fname = "ptab1", digits = 3)
tab2 <- table1(sex ~ flp + body_mass_g + bill_length_mm | island, data = p1)  |>
latex(theme = theme_nejm, fname = "ptab2", digits = 3)
tab3 <- table1(sex ~ flp + body_mass_g + bill_length_mm | island, data = p1)  |>
latex(theme = theme_nejm, fname = "ptab3", digits = 3)
tab4 <- table1(sex ~ flp + body_mass_g + bill_length_mm + island, data = p1)  |>
latex(theme = theme_nejm, fname = "ptab4", digits = 3)
tab5 <- table1(sex ~ island + flp + body_mass_g + bill_length_mm, data = p1)  |>
latex(theme = theme_nejm, fname = "ptab5", digits = 3)


```



\zzfigtex{tables/ptab1.pdf}{test 1}{5in}{5in}
\zzfigtex{tables/ptab2.pdf}{test 2}{5in}{5in}
\zzfigtex{tables/ptab3.pdf}{test 3}{5in}{5in}
\zzfigtex{tables/ptab4.pdf}{test 4}{5in}{5in}
\zzfigtex{tables/ptab5.pdf}{test 5}{5in}{5in}

